### ISSUE TITLE
Leaflet Rendering is not working in R 3.6.3

### ISSUE THREAD

**Issue by tsviken** [bupaverse/processanimateR#27] opened 2020-03-10 20:08 UTC
Hi.

After the most recent R studio upgrade the leaflet rendering is not working correctly.  

Running the example from the documentation the  produced new 1 warning:

`animate_process(example_log,
  renderer = renderer_leaflet(
    node_coordinates = data.frame(
       act = c("A", "B", "C", "D", "Start", "End"),
       lat = c(63.443680, 63.426925, 63.409207, 63.422336, 63.450950, 63.419706),
       lng = c(10.383625, 10.396972, 10.406418, 10.432119, 10.383368, 10.252347),
       stringsAsFactors = FALSE),
    edge_coordinates = data.frame(
       act_from = c("B"),
       act_to = c("C"),
       lat = c(63.419207),
       lng = c(10.386418),
       stringsAsFactors = FALSE),
    options = list(center = c(63.412273, 10.399590), zoom = 12)),
  duration = 5, repeat_count = Inf)`

`2: In stri_replace_all_regex(string, pattern, fix_replacement(replacement),  :
  argument is not an atomic vector; coercing`

Running the same example on R version 3.6.1 (2019-07-05) -- "Action of the Toes" with processanimateR v1.01 works flawlessly.

Technical specs of the newest combination that's not working:
Rstudio:  R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
processanimateR v1.0.2

**Comment by fmannhardt** [comment] 2020-03-11 11:53
Thanks for reporting, I will try to check this out in the next few days. I changed bits in the implementation in v1.0.2, so likely a regression on my side.

**Comment by tsviken** [comment] 2020-03-11 12:27
Thanks :)

**Comment by fmannhardt** [comment] 2020-03-13 15:21
Could reproduce it with R 3.6.3 and the CRAN released version, but it seems to be fixed in the development version. Could you please also try on your side:

```
# install the remotes package
source("https://install-github.me/r-lib/remotes")

# use remotes to install the latest version of processanimateR
remotes::install_github("bupaverse/processanimateR")
```

And then repeat the command? There may be a new warning due to change of the artificial start and end activities in processmapR, but that one should not lead to an error.

**Comment by tsviken** [comment] 2020-03-13 15:35
Hi, did a quick test on it. It works now on my end. I also recieve the error message you mention

**Comment by fmannhardt** [comment] 2020-03-13 15:41
Good. That warning is only since artificial start and end nodes have a different label now (to avoid collision with likely names). Will try to add an option to get rid of the need for artificial activities as this does not make much sense for geographical maps.

**Closed by fmannhardt** 2020-03-13 15:41 UTC
Labels: bug
